github-uri: https://github.com/tkaburagi1214/pcfdemoapp.git  # Change this to your fork
github-branch: master
github-private-key: |
   -----BEGIN RSA PRIVATE KEY-----
   MIIEogIBAAKCAQEAt+FEpWzffT/jAGlUVj7EK8ATYCy2nFz5iPP2cM5JeRzU/dHA
   yjY7AMMjtd7wciY9Sg+Yha6ojegy7kBGimElS1QEtX7/h5PcwmRFqzqFpd6vZcG9
   QwaiGRPSX9raIB4prOnSuv2M2DLrupPzW1GPlnchEvk8G4PJHT3EjAmUvW7pMtBE
   VJmUklwsnIsiVIUv+6PyzRKOtFbGVCXDQExpxGiN2XRbqYXwA6ZG9pvHdh/ruF8G
   rLry7ey2tSRNI6cibS1RHZkzeOTBvteBj8G8j/BYKITs35hRSx7LKgHDi+FlN9GR
   6BsErg2kqSWC5K60OPHVpBHez4iHJOVzPrmJ8QIDAQABAoIBACQSzH3LmxieRPFa
   uJHm5GNU3jg67WRFlSq5+bntrlpVPq/Ay5qgAvlGTyYp42/xcoqp/pkTR7v3Nq6o
   623QWxmpFPdqP8UgS+nS9BwAciG1SyGiXXfdwEU9L0Ng0vQEFtb2VEIc5dmwO7Cx
   v8dFe+7f1hw7yv/23aif6oQyiPyUhRMiXYNZZFkKhJPhg6q/UtHbfWUECPzLtv6+
   Xqyk5sCvUBd6u+QCd1aivW7lgK0A9y1tg+IANAgb30XVnyKWDL9ktEwNV2Wh3euZ
   a1LZG2IBGTn53COX3GvM29ZkgOP1NCNo6XdfR7I1PbolV/KUEaiaJlo0AnJAokBG
   FNlPN1UCgYEA8KmMazfPxE8upm0+tDJXonRQUOmC+QT7ym+V5pD0MbkFaqsNAhQb
   ZAZ0aPZdUNq563jIuYFqpe+lIMCwL5MxECuwubqdSuolklDnD6b0XfLi0UE0Pkg9
   iiWAa4VTEbh7sqtNo5C+7nd7EzHhEPnicAIWnoaXm2gh3Q3fGjI1NDsCgYEAw5lO
   B6GKAPT4ApUz8sH3cUVVmTzBTaEVvIu12DRhcytiKo12wQIa5QK1a4SdpeLoPMVg
   olwI9TKwLCHLNVB7gB4ilBD599SCyH+dHhjmQRAXR2ekWN0p6kwU7tIX5oWaD/Xs
   yVw5HwEXiZLDdR/cfU5+sDBdwdsGSJYDPT6xM8MCgYBvgzCEccz8um/0P8SBPJ5s
   sRaSF1FPz6ZYC9JajqoH7CJ9ZZrWbriuZWtFQ3rDv0XMvR/NDRF8qAlMntxEfyCJ
   zKTLupOtpccZABHAp+ytJ6E/ssXhYhnZzDywFYwDNwdiJ4wHEUfXOVe28jLGafMp
   UV5nwBe5s8uVIRtSiRcsBwKBgHwvNDxiEmVjIqc5JX9GKRzwYVVmHnB0CoHnze9T
   6l8dtzi/Ehueg4bMvnRiAVlWBA65Xg4XEtTidrm+Ru81hwOjnl6VnK79bH9xjkaS
   lnXOiokaQ1zsJfWMkmnCV8xTHKpvgAOkGtwVbGU7Gf+d1/ZyxLqGKrCup4GkRLA4
   wnbTAoGATXtnpPnLLayJkJD1wUiaXuTlGixREQitSynBVBXUBZQZctaRf4dam3Ji
   bsfJ6PpuirCSDQumUBp8qORYOZoLmsLj6mJjfvOKDVu1N+/bnZtDK1TsCFXVQ5hr
   IeH+PFFJjRQyLuf2oTAPcJ/huOMqYzonikDIwfZlEahDGFnh4KI=
   -----END RSA PRIVATE KEY-----
gcs-bucket-release-candidates: pcfdemoapp-release-candidates
gcs-bucket-releases: pcfdemoapp-releases
gcs-bucket-version: pcfdemoapp-version
cf-api: "https://api.system.kabdev.xyz"  # Change the following to match your Cloud Foundry environment
cf-org: "pcfdemoapp"
cf-username: "kab"
cf-password: "kab"
cf-space-staging: "staging"
cf-space-prod: "production"
cf-manifest-host-staging: "pcfdemoapp-staging"
cf-manifest-host-prod: "pcfdemoapp"
gcs-key:  |
          {
            "type": "service_account",
            "project_id": "fe-tkaburagi",
            "private_key_id": "36f2bff6408f87b21839b6be05fb1063fc1441fc",
            "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2orvxgiCxgvq3\np8jFDRJ52XSoPLR+XlUWYxGALarzz8Uf8qErHYpgOsXycOGhiAchv6hbirdqs71J\nNU0pt7i3PcQKyD0LQs+CMkEcPV1XU+T0IDCysHydSLrBfuF2Z5l45GpQJ3w8DXCO\nrj2JsYnanaNqVIWzdRkrCYcn6Mw9gZohCGT9SORkOyvBOAsZemNCuAU39HY5RXuU\nin+Vz8ZLhu0EKffQPFPwrE1xgnBpSvksVfnUCWypUZfMz099kl8makDhkaCZBpNE\nIx7rpPF7Sl621TnwYAf7AFTOixvIVVaiKuagIVEX9YqWS8hnKySLoCXMXYIrfJHj\nZCot4xoZAgMBAAECggEATPrfvAaM0DV0hweuHLyLTpfFT4oyy9boB2Ufgcb9+QFY\nxcQHgbxUUIZFXBCPUf4bf3KgvGEGOW/kN2DDkvNw5K+gm6jV7hKtk2OqRQRqfP4M\nEYgl7pNsGwGGUjuwPa+iJS4lz34tI8TIbiNsJccS43YxZIaWylLvlk/QS5aYy81I\nAKRD0pse2mOY2HLLgH9FJ2d656B26lemIz09oLMyCMw6nokrqXndB5svuSL5l2rC\nTOiSyV1W7GCZ0cQFkFk4bizLXsoOS8BEeNVmWlzzcvjGG4Dolr6OzJ6Up/RTptVe\n7M6JgAimig15jR1O/4lDUWUrBIirNJZEr7EzF1idxwKBgQDceIfK3puHDhJVyKVG\nfEk3gg5FFU7PxtNZVK7V96Hrx0PxmPrMQLnUpBW/+HeFnn2t/wE2f2FAMG1dDNti\ng4d6ATYJ3eXngtyTKZ6KRRhZ762QPrNExbhhKrVMhrnxMMZd0SD+zBE9Mld0S9pr\ng8qP2QuHnwOFb0AwchoFSnWPjwKBgQDUEVMBo4D26sEuflMltOVPhM7RSwbS6NeB\nlu+0Z+DE6zrm0bxD/QAEDlT0VFnT2zAuIZqyu7SVt10CuEyj4Ekec6Mauq99S22j\nEQZJVgakRTNqhYrjRQwbIMcObd6Ufpw41thZfRYQV0rN0X6N1fXOmWozk4FPwW0H\nFvXsXstn1wKBgBa824xhrvqbyepM+jatxMNTx3L6gplNMSjqYemxU2LEt04ob902\n47N5hMC6uGDwepfCT/a15mq/U9gf5lRfqk47573Ww8o/pc4Loc0y2RMVc/oHbWev\nWJe01uPglTa5yAuO8O82TqTYF0roM8uY2QBC6zx+etd9JMqaSfK3vi4jAoGAOYOR\nTYp4eX7lcaSVDE7pOg28wYpliWHYwK6cyAK8NOvPB7auJopBLNhuNe2ChzCU+o3m\nlL7PlSMruIcfUfqMGhQmkiM7YPHKBEWjvNP17StPbH5XUpfxVpInKkSl7wP/fnLW\nLj78cuYZxYQhnHoAtk1pPh+tHGJLHXcer0JuS/UCgYEA1DgikiQzLYRyICrK56C8\nYSZNQ2aB5YB6T6kgjcCn9gZfQ2a80tLq3lQsjOOsfcNA/wigyGmgeWFbDoHDQxUY\n7ABecPP9uT9mX86sMPPQu+3HYRgpxxojACmczz49gkPJ9ONVFIqVcbUCI8ngoV55\nkZ90tSajd41mTidS7DM9Eeo=\n-----END PRIVATE KEY-----\n",
            "client_email": "gcd-owner@fe-tkaburagi.iam.gserviceaccount.com",
            "client_id": "103706751692505011588",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://accounts.google.com/o/oauth2/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/gcd-owner%40fe-tkaburagi.iam.gserviceaccount.com"
          }
